FirstSaleDate = CALCULATE(
    MIN(Sales[Order Date])  
)
FirstWeekSales = CALCULATE(
    Sales[Sales Amount],
     DATESBETWEEN(Sales[Order Date],'Product'[FirstSaleDate],'Product'[FirstSaleDate]+7)           
)
